import torch
from .crs_baseline import CRS_BASELINE

def load_crs_baseline(
    lm_type="meta-llama/Llama-3.2-1B-Instruct",
    retrieval_type="bm25",
    item_db_name: str = "talkpl-ai/TalkPlayData-Challenge-Track-Metadata",
    user_db_name: str = "talkpl-ai/TalkPlayData-Challenge-User-Metadata",
    track_split_types: list[str] = ["all_tracks"],
    user_split_types: list[str] = ["all_users"],
    corpus_types: list[str] = ["track_name", "artist_name", "album_name"],
    cache_dir="./cache",
    device="cuda",
    attn_implementation="eager",
    dtype=torch.bfloat16,
    reranker_type=None,
    reranker_kwargs=None,
    retrieve_topk=20,
    final_topk=20,
    retrieval_kwargs=None,
    include_user_profile_in_retrieval=False,
    response_topk=1,
    generation_mode="default",
    max_response_tokens=64,
    lm_kwargs=None,
    load_lm=True,
):
    return CRS_BASELINE(
        lm_type,
        retrieval_type,
        item_db_name,
        user_db_name,
        track_split_types,
        user_split_types,
        corpus_types,
        cache_dir,
        device,
        attn_implementation,
        dtype,
        reranker_type=reranker_type,
        reranker_kwargs=reranker_kwargs,
        retrieve_topk=retrieve_topk,
        final_topk=final_topk,
        retrieval_kwargs=retrieval_kwargs,
        include_user_profile_in_retrieval=include_user_profile_in_retrieval,
        response_topk=response_topk,
        generation_mode=generation_mode,
        max_response_tokens=max_response_tokens,
        lm_kwargs=lm_kwargs,
        load_lm=load_lm,
    )
